# Generated by Django 3.2.9 on 2021-11-14 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_otplog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otplog',
            options={'ordering': ('-timestamp',)},
        ),
    ]
