# Generated by Django 3.2.9 on 2021-11-14 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_trx_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otplog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 14, 19, 45, 21, 832024)),
        ),
    ]
