# Generated by Django 3.2.9 on 2021-11-14 19:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_otplog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otplog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 14, 19, 48, 2, 542270, tzinfo=utc)),
        ),
    ]
