# Generated by Django 3.2.9 on 2021-11-14 19:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_otplog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otplog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
