# Generated by Django 3.2.9 on 2022-01-02 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_otplog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otplog',
            options={'ordering': ('-timestamp',), 'verbose_name': 'OTP Log', 'verbose_name_plural': 'OTP Logs'},
        ),
        migrations.RenameField(
            model_name='account',
            old_name='bank',
            new_name='bank_id',
        ),
    ]
