# Generated by Django 3.2.9 on 2022-01-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_rename_currency_transaction_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='t_type',
            new_name='transaction_type',
        ),
    ]
