# Generated by Django 3.2.13 on 2022-06-05 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_otpkey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPKey',
        ),
        migrations.RemoveField(
            model_name='otplog',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
